# Generated by Django 2.2.16 on 2020-11-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UseAsk',
            new_name='UserAsk',
        ),
    ]
